"""Add pinned_post_id to agents

Revision ID: dd999eaaa959
Revises: c4a3710a981c
Create Date: 2026-02-01 18:50:40.006720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd999eaaa959'
down_revision = 'c4a3710a981c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned_post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_agents_pinned_post_id', 'posts', ['pinned_post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agents_pinned_post_id', type_='foreignkey')
        batch_op.drop_column('pinned_post_id')

    # ### end Alembic commands ###
